// delay
export const SAVE_CONTENT_DELAY_MS = 5_000;
export const SWIPE_ACTION_FEEDBACK_DURATION_MS = 300; // Reduced from 500ms for faster feedback
export const SWIPE_ACTION_CARD_REMOVAL_DELAY_MS = 400; // Delay before removing card after feedback animation
export const DEFAULT_HAPTIC_DURATION_MS = 120;

// swipe action sizing
export const SWIPE_ACTION_BUTTON_WIDTH = 80;
export const SWIPE_MENU_DAMPING = 0.65;

// content feed swipe (Home)
export const HOME_TAB_LEFT_ACTION_COUNT = 2;
export const HOME_TAB_RIGHT_ACTION_COUNT = 1;
export const HOME_TAB_LEFT_ACTION_WIDTH = SWIPE_ACTION_BUTTON_WIDTH * HOME_TAB_LEFT_ACTION_COUNT;
export const HOME_TAB_RIGHT_ACTION_WIDTH = SWIPE_ACTION_BUTTON_WIDTH * HOME_TAB_RIGHT_ACTION_COUNT;

// recommend feed swipe
export const RECOMMEND_TAB_LEFT_ACTION_COUNT = 1;
export const RECOMMEND_TAB_RIGHT_ACTION_COUNT = 1;
export const RECOMMEND_TAB_LEFT_ACTION_WIDTH =
  SWIPE_ACTION_BUTTON_WIDTH * RECOMMEND_TAB_LEFT_ACTION_COUNT;
export const RECOMMEND_TAB_RIGHT_ACTION_WIDTH =
  SWIPE_ACTION_BUTTON_WIDTH * RECOMMEND_TAB_RIGHT_ACTION_COUNT;

// archive swipe
export const ARCHIVE_TAB_LEFT_ACTION_COUNT = 2;
export const ARCHIVE_TAB_RIGHT_ACTION_COUNT = 1;
export const ARCHIVE_TAB_LEFT_ACTION_WIDTH =
  SWIPE_ACTION_BUTTON_WIDTH * ARCHIVE_TAB_LEFT_ACTION_COUNT;
export const ARCHIVE_TAB_RIGHT_ACTION_WIDTH =
  SWIPE_ACTION_BUTTON_WIDTH * ARCHIVE_TAB_RIGHT_ACTION_COUNT;
