export const SAVE_CONTENT_DELAY_MS = 5_000;

export const LEFT_ACTION_WIDTH = 160;
export const RIGHT_ACTION_WIDTH = 96;
export const SWIPE_MENU_DAMPING = 0.65;
export const RECOMMEND_LEFT_ACTION_WIDTH = 140;
export const RECOMMEND_RIGHT_ACTION_WIDTH = 120;
export const TIMELINE_LEFT_ACTION_WIDTH = 120;
export const TIMELINE_RIGHT_ACTION_WIDTH = 120;
